known_failures:
  # Neutron operator
  - test: 'tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON'
    deployment:
      - 'overcloud'
    releases:
      - name: 'master'
        reason: 'No controller'
        lp: 'http://no.bug'
    jobs:
      - neutron-operator
  - test: 'tempest.api.network.admin.test_ports.PortsAdminExtendedAttrsIpV6TestJSON'
    deployment:
      - 'overcloud'
    releases:
      - name: 'master'
        reason: 'No controller'
        lp: 'http://no.bug'
    jobs:
      - neutron-operator
  - test: 'tempest.api.network.admin.test_ports.PortsAdminExtendedAttrsTestJSON'
    deployment:
      - 'overcloud'
    releases:
      - name: 'master'
        reason: 'No controller'
        lp: 'http://no.bug'
    jobs:
      - neutron-operator
  # Cinder operator
  - test: 'tempest.api.volume.admin.test_volume_types.VolumeTypesTest.test_volume_crud_with_volume_type_and_extra_specs'
    deployment:
      - 'overcloud'
    releases:
      - name: 'master'
        reason: 'No controller'
        lp: 'http://no.bug'
    jobs:
      - cinder-operator
  - test: 'tempest.api.volume.admin.test_volumes_actions.VolumesActionsTest.test_force_detach_volume'
    deployment:
      - 'overcloud'
    releases:
      - name: 'master'
        reason: 'No controller'
        lp: 'http://no.bug'
    jobs:
      - cinder-operator
  - test: 'tempest.api.volume.test_volumes_actions.VolumesActionsTest.test_attach_detach_volume_to_instance'
    deployment:
      - 'overcloud'
    releases:
      - name: 'master'
        reason: 'No controller'
        lp: 'http://no.bug'
    jobs:
      - cinder-operator
  - test: 'tempest.api.volume.test_volumes_actions.VolumesActionsTest.test_get_volume_attachment'
    deployment:
      - 'overcloud'
    releases:
      - name: 'master'
        reason: 'No controller'
        lp: 'http://no.bug'
    jobs:
      - cinder-operator
  - test: 'tempest.api.volume.test_volumes_backup.VolumesBackupsTest.test_backup_create_attached_volume'
    deployment:
      - 'overcloud'
    releases:
      - name: 'master'
        reason: 'No controller'
        lp: 'http://no.bug'
    jobs:
      - cinder-operator
  - test: 'tempest.api.volume.test_volumes_backup.VolumesBackupsTest.test_volume_backup_create_get_detailed_list_restore_delete'
    deployment:
      - 'overcloud'
    releases:
      - name: 'master'
        reason: 'No controller'
        lp: 'http://no.bug'
    jobs:
      - cinder-operator
  - test: 'tempest.api.volume.test_volumes_negative.VolumesNegativeTest.test_attach_volumes_with_nonexistent_volume_id'
    deployment:
      - 'overcloud'
    releases:
      - name: 'master'
        reason: 'No controller'
        lp: 'http://no.bug'
    jobs:
      - cinder-operator
  - test: 'tempest.api.volume.test_volumes_snapshots.VolumesSnapshotTestJSON.test_snapshot_create_delete_with_volume_in_use'
    deployment:
      - 'overcloud'
    releases:
      - name: 'master'
        reason: 'No controller'
        lp: 'http://no.bug'
    jobs:
      - cinder-operator
  - test: 'tempest.api.volume.test_volumes_snapshots.VolumesSnapshotTestJSON.test_snapshot_create_offline_delete_online'
    deployment:
      - 'overcloud'
    releases:
      - name: 'master'
        reason: 'No controller'
        lp: 'http://no.bug'
    jobs:
      - cinder-operator
  # Nova operator
  - test: ServerActionsV293TestJSON
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Cinder volume not enabled
        lp: http://no.bug
    jobs:
      - nova-operator
  - test: test_admin_delete_servers_of_others
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Cinder volume not enabled
        lp: http://no.bug
    jobs:
      - nova-operator
  - test: test_get_server_diagnostics
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Cinder volume not enabled
        lp: http://no.bug
    jobs:
      - nova-operator
  - test: test_create_image_from_paused_server
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Cinder volume not enabled
        lp: http://no.bug
    jobs:
      - nova-operator
  - test: test_delete_server_while_in_attached_volume
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Cinder volume not enabled
        lp: http://no.bug
    jobs:
      - nova-operator
  - test: Tagged
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Cinder volume not enabled
        lp: http://no.bug
    jobs:
      - nova-operator
  - test: _volume
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Cinder volume not enabled
        lp: http://no.bug
    jobs:
      - nova-operator
  - test: Volume
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Cinder volume not enabled
        lp: http://no.bug
    jobs:
      - nova-operator
  - test: tempest.api.compute.admin.test_volumes_negative.VolumesAdminNegativeTest
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Cinder volume not enabled
        lp: http://no.bug
    jobs:
      - nova-operator
  - test: tempest.api.compute.servers.test_servers_negative.ServersNegativeTestJSON.test_create_server_from_non_bootable_volume
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Cinder volume not enabled
        lp: http://no.bug
    jobs:
      - nova-operator
  - test: tempest.api.compute.servers.test_servers_negative.ServersNegativeTestJSON.test_create_server_invalid_bdm_in_2nd_dict
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Cinder volume not enabled
        lp: http://no.bug
    jobs:
      - nova-operator
  - test: manila_tempest_tests.tests.api.test_share_network_subnets.ShareNetworkSubnetsTest.test_create_delete_subnet
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Fix not landed yet
        lp: http://no.bug
    jobs:
      - manila-operator
  - test: tempest.api.compute.admin.test_live_migration_negative.LiveMigrationNegativeTest.test_live_block_migration_suspended
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Test env does not have compute
        lp: http://no.bug
    jobs:
      - nova-operator
  - test: tempest.api.compute.admin.test_live_migration_negative.LiveMigrationNegativeTest.test_invalid_host_for_migration
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Test env does not have compute
        lp: http://no.bug
    jobs:
      - nova-operator
  # TODO (rlandy) remove when https://issues.redhat.com/browse/OSPCIX-126 is fixed
  - test: tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_mtu_sized_frames
    deployment:
      - overcloud
    releases:
      - name: master
        reason: IBM cloud exposes MTU setup differences exposing a real issue
        lp: https://issues.redhat.com/browse/OSPCIX-126
      - name: antelope
        reason: IBM cloud exposes MTU setup differences exposing a real issue
        lp: https://issues.redhat.com/browse/OSPCIX-126
    jobs: []
  - test: ironic_tempest_plugin.tests.api.admin.test_allocations.TestAllocations
    deployment:
      - overcloud
    releases:
      - name: master
        reason: Test bug being fixed in caracal.
        lp: https://bugs.launchpad.net/ironic/+bug/2054722
    jobs:
      - ironic-operator
  - test: ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesVif.test_vif_attach_node_doesnt_exist
    deployment:
      - overcloud
    releases:
      - name: master
        reason: The test is not adjusted for the podified env.
        lp: https://bugs.launchpad.net/ironic/+bug/2065378
    jobs:
      - ironic-operator
  - test: ironic_tempest_plugin.tests.api.admin.test_nodes.TestNodesVif.test_vif_detach_no_args
    deployment:
      - overcloud
    releases:
      - name: master
        reason: The test is not adjusted for the podified env.
        lp: https://bugs.launchpad.net/ironic/+bug/2065378
    jobs:
      - ironic-operator
